// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackageTrackingAPI.DAL;

#nullable disable

namespace PackageTrackingAPI.DAL.Migrations
{
    [DbContext(typeof(PackageTrackingContext))]
    [Migration("20250411224444_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Package", b =>
                {
                    b.Property<int>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackageID");

                    b.HasIndex("SenderID");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("PackageTrackingAPI.Models.Alert", b =>
                {
                    b.Property<int>("AlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertID"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AlertID");

                    b.HasIndex("UserID");

                    b.ToTable("Alerts");

                    b.HasData(
                        new
                        {
                            AlertID = 1,
                            Message = "Package delayed due to weather conditions.",
                            PackageID = 101,
                            Timestamp = new DateTime(2025, 4, 11, 5, 30, 0, 0, DateTimeKind.Local),
                            UserID = 1
                        },
                        new
                        {
                            AlertID = 2,
                            Message = "Package out for delivery.",
                            PackageID = 102,
                            Timestamp = new DateTime(2025, 4, 11, 7, 45, 0, 0, DateTimeKind.Local),
                            UserID = 2
                        },
                        new
                        {
                            AlertID = 3,
                            Message = "Package delivered successfully.",
                            PackageID = 103,
                            Timestamp = new DateTime(2025, 4, 10, 11, 20, 0, 0, DateTimeKind.Local),
                            UserID = 3
                        },
                        new
                        {
                            AlertID = 4,
                            Message = "Package returned to sender.",
                            PackageID = 104,
                            Timestamp = new DateTime(2025, 4, 9, 9, 5, 0, 0, DateTimeKind.Local),
                            UserID = 4
                        },
                        new
                        {
                            AlertID = 5,
                            Message = "Package pending at pickup location.",
                            PackageID = 105,
                            Timestamp = new DateTime(2025, 4, 8, 13, 30, 0, 0, DateTimeKind.Local),
                            UserID = 5
                        });
                });

            modelBuilder.Entity("PackageTrackingAPI.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "alice.johnson@example.com",
                            Name = "Alice Johnson",
                            PasswordHash = "hashed_password_1",
                            Role = "Admin"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "bob.smith@example.com",
                            Name = "Bob Smith",
                            PasswordHash = "hashed_password_2",
                            Role = "User"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "charlie.brown@example.com",
                            Name = "Charlie Brown",
                            PasswordHash = "hashed_password_3",
                            Role = "User"
                        },
                        new
                        {
                            UserID = 4,
                            Email = "david.wilson@example.com",
                            Name = "David Wilson",
                            PasswordHash = "hashed_password_4",
                            Role = "Manager"
                        },
                        new
                        {
                            UserID = 5,
                            Email = "emma.davis@example.com",
                            Name = "Emma Davis",
                            PasswordHash = "hashed_password_5",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("TrackingEvent", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("EventID");

                    b.HasIndex("PackageID");

                    b.ToTable("TrackingEvents");
                });

            modelBuilder.Entity("Package", b =>
                {
                    b.HasOne("PackageTrackingAPI.Models.User", "Sender")
                        .WithMany("Packages")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PackageTrackingAPI.Models.Alert", b =>
                {
                    b.HasOne("PackageTrackingAPI.Models.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrackingEvent", b =>
                {
                    b.HasOne("Package", "Package")
                        .WithMany("TrackingEvents")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Package", b =>
                {
                    b.Navigation("TrackingEvents");
                });

            modelBuilder.Entity("PackageTrackingAPI.Models.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
